# Site
name: "Joy of Whisky"
title: "Joy of Whisky"
description: "A small whisky note site"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
destination: docs/

# Authors
authors:
  tony:
    name: Tony
    display_name: Tony
    avatar: 'assets/images/avatar.png'
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "M0g1c1an"


# Collections
collections:
  distillery_infos:
    defaults:
      layout: post
    output: true
    permalink: distillery/:path/details.html
  bottler_infos:
    defaults:
      layout: post
    output: true
    permalink: bottler/:path/details.html


defaults:
  - scope:
      type: distilleries
    values:
      layout: distillery
      permalink: distillery/:path/
  - scope:
      type: bottlers 
    values:
      layout: distillery
      permalink: bottler/:path/


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
    - bottler
    - distillery
  layout: archive
  permalinks:
    category: '/category/:name/'
    bottler: '/bottler/:name/'
    distillery: '/distillery/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
