# Site
name: "Whisky Young"
title: "Whisky Young"
description: "一个普通的威士忌小网站"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
url: 'https://mogic1an.github.io'
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: blog/:title/
destination: _site/

# Authors
authors:
  tony:
    name: Tony
    display_name: Tony
    avatar: 'assets/images/tony.jpg'
    email: haow0628@gmail.com
    description: "摆烂计算机在读，威士忌小白，搞笑贝斯手。"
  brian:
    name: Brian
    display_name: Brian
    avatar: 'assets/images/brian.jpg'
    email: gy1693136575@163.com
    description: "英专在读，威士忌爱好者。喜欢恐怖海峡和金汤力。"



# Collections
collections:
  notes:
    archive: true
    defaults:
      layout: post
    output: true
    permalink: note/:path/
  distillery_infos:
    defaults:
      layout: info
    output: true
    permalink: distillery/:path/details.html
  bottler_infos:
    defaults:
      layout: info
    output: true
    permalink: bottler/:path/details.html


defaults:
  - scope:
      type: distilleries
    values:
      layout: distillery
      permalink: distillery/:path/
  - scope:
      type: bottlers 
    values:
      layout: bottler
      permalink: bottler/:path/


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, vendor, 
  gen_index.js, doc.json] # for static search
